import { OrderProps } from "./columns";

export const orders: OrderProps[] = [
  {
    order: "ORD001",
    status: "Pending",
    lastOrder: "12/12/2020",
    method: "Credit Card",
  },
  {
    order: "ORD002",
    status: "Processing",
    lastOrder: "01/05/2021",
    method: "PayPal",
  },
  {
    order: "ORD003",
    status: "Completed",
    lastOrder: "08/20/2021",
    method: "Credit Card",
  },
  {
    order: "ORD004",
    status: "Pending",
    lastOrder: "03/15/2021",
    method: "Credit Card",
  },
  {
    order: "ORD005",
    status: "Processing",
    lastOrder: "11/30/2020",
    method: "PayPal",
  },
  {
    order: "ORD006",
    status: "Pending",
    lastOrder: "05/22/2021",
    method: "Credit Card",
  },
  {
    order: "ORD007",
    status: "Completed",
    lastOrder: "09/10/2021",
    method: "Credit Card",
  },
  {
    order: "ORD008",
    status: "Processing",
    lastOrder: "07/07/2021",
    method: "PayPal",
  },
  {
    order: "ORD009",
    status: "Pending",
    lastOrder: "04/18/2021",
    method: "Credit Card",
  },
  {
    order: "ORD010",
    status: "Completed",
    lastOrder: "02/28/2021",
    method: "Credit Card",
  },
  {
    order: "ORD011",
    status: "Processing",
    lastOrder: "10/05/2021",
    method: "PayPal",
  },
  {
    order: "ORD012",
    status: "Pending",
    lastOrder: "06/11/2021",
    method: "Credit Card",
  },
  {
    order: "ORD013",
    status: "Processing",
    lastOrder: "12/25/2020",
    method: "PayPal",
  },
  {
    order: "ORD014",
    status: "Pending",
    lastOrder: "03/02/2021",
    method: "Credit Card",
  },
  {
    order: "ORD015",
    status: "Completed",
    lastOrder: "08/15/2021",
    method: "Credit Card",
  },
  {
    order: "ORD016",
    status: "Processing",
    lastOrder: "11/08/2020",
    method: "PayPal",
  },
  {
    order: "ORD017",
    status: "Pending",
    lastOrder: "05/01/2021",
    method: "Credit Card",
  },
  {
    order: "ORD018",
    status: "Completed",
    lastOrder: "09/22/2021",
    method: "Credit Card",
  },
  {
    order: "ORD019",
    status: "Processing",
    lastOrder: "07/13/2021",
    method: "PayPal",
  },
  {
    order: "ORD020",
    status: "Pending",
    lastOrder: "01/30/2021",
    method: "Credit Card",
  },
  {
    order: "ORD021",
    status: "Processing",
    lastOrder: "06/25/2021",
    method: "PayPal",
  },
  {
    order: "ORD022",
    status: "Completed",
    lastOrder: "10/12/2020",
    method: "Credit Card",
  },
  {
    order: "ORD023",
    status: "Pending",
    lastOrder: "04/03/2021",
    method: "Credit Card",
  },
  {
    order: "ORD024",
    status: "Processing",
    lastOrder: "11/18/2021",
    method: "PayPal",
  },
  {
    order: "ORD025",
    status: "Pending",
    lastOrder: "07/01/2021",
    method: "Credit Card",
  },
  {
    order: "ORD026",
    status: "Completed",
    lastOrder: "09/14/2021",
    method: "Credit Card",
  },
  {
    order: "ORD027",
    status: "Processing",
    lastOrder: "05/05/2021",
    method: "PayPal",
  },
  {
    order: "ORD028",
    status: "Pending",
    lastOrder: "02/20/2021",
    method: "Credit Card",
  },
  {
    order: "ORD029",
    status: "Completed",
    lastOrder: "08/10/2021",
    method: "Credit Card",
  },
  {
    order: "ORD030",
    status: "Pending",
    lastOrder: "10/30/2020",
    method: "PayPal",
  },
];
